### ISSUE TITLE
RSEA-3310 Seleção de ida e volta no mesmo dia da busca não gera mensagem HELIO

### ISSUE THREAD

**Issue by henrique-softvaro** [henrique-softvaro/bugs-release-r1-2021#2]
[Squad Redesign][Mobile][Buscador] 2 destinos - combinação G3/YY não gera mensagem de erro

**Comment by heliofazollo** [comment]
https://user-images.githubusercontent.com/63798882/150577950-b92af988-5cab-4a00-9c32-0c6644c52d0c.mov
