### ISSUE TITLE
RSEA-3309 2 destinos - tela em branco no primeiro destino

### ISSUE THREAD

**Issue by henrique-softvaro** [henrique-softvaro/bugs-release-r1-2021#3]
[Squad Redesign][Mobile IOS][Buscador] 2 destinos - tela em branco no primeiro destino

**Comment by frederico-reis-softvaro** [comment]
[bug 2 destinos embarque.pdf](https://github.com/henrique-softvaro/bugs-release-r1-2021/files/7915478/bug.2.destinos.embarque.pdf)

**Comment by frederico-reis-softvaro** [comment]
[bug destino ios.pdf](https://github.com/henrique-softvaro/bugs-release-r1-2021/files/7915487/bug.destino.ios.pdf)

**Comment by frederico-reis-softvaro** [comment]
https://user-images.githubusercontent.com/86992602/151061606-7621b786-d367-4b37-875e-c6fc5ab26eb4.mov

Tela branca ao abrir modal de pesquisa de aeroporto resolvida

**Comment by heliofazollo** [comment]
![Captura de Tela 2022-01-27 às 18 16 08](https://user-images.githubusercontent.com/63798882/151445363-78635168-bd2b-4ea9-b19e-2a4fed49e93b.png)
![Captura de Tela 2022-01-27 às 18 16 24](https://user-images.githubusercontent.com/63798882/151445372-5680da4c-9456-4150-ab8d-cd70febd8b8d.png)
![Captura de Tela 2022-01-27 às 18 16 35](https://user-images.githubusercontent.com/63798882/151445375-a080ef1a-cdeb-412d-9d32-b412c6d222f0.png)
![Captura de Tela 2022-01-27 às 18 16 45](https://user-images.githubusercontent.com/63798882/151445377-ef585126-3da9-433e-9404-ca5d71f4117a.png)
![Captura de Tela 2022-01-27 às 18 16 58](https://user-images.githubusercontent.com/63798882/151445383-85faab04-44eb-4d07-ab9c-b1b555978bbb.png)
![Captura de Tela 2022-01-27 às 18 17 26](https://user-images.githubusercontent.com/63798882/151445388-8ce3ab5f-f82e-43d7-90f9-aebe16dfd051.png)
![Captura de Tela 2022-01-27 às 18 17 39](https://user-images.githubusercontent.com/63798882/151445394-b9e36da7-7bcc-41a7-84e4-fffa6546fef3.png)
![Captura de Tela 2022-01-27 às 18 18 05](https://user-images.githubusercontent.com/63798882/151445397-c5155756-bf68-4de3-9383-9f17866b1196.png)
![Captura de Tela 2022-01-27 às 18 18 16](https://user-images.githubusercontent.com/63798882/151445402-152bca27-6c01-4f2a-b74c-2b77f1a42862.png)
