### ISSUE TITLE
RSEA-3321 | Squad Redesign | Home | Portal | Buscador Voo | Geolocalização para 2 Destinos

### ISSUE THREAD

**Issue by frederico-reis-softvaro** [henrique-softvaro/bugs-release-r1-2021#30]
Ao entrar no Portal, selecionar a opção 2 Destinos e permitir a Geolocalização, está sendo sugerido o aeroporto mais próxmios no campo origem para o 1º e 2º destino. Deveria ser somente para o 1º destino.

![image-20220121-173734](https://user-images.githubusercontent.com/86992602/150576284-c0e89289-b963-4a3a-b119-ca153f13a5cd.png)

**Comment by heliofazollo** [comment]
![Captura de Tela 2022-01-22 às 15 35 59](https://user-images.githubusercontent.com/63798882/150651249-ef6fd9f4-d9f2-4a5c-bb5c-d34c133ee7c0.png)
![Captura de Tela 2022-01-22 às 15 35 44](https://user-images.githubusercontent.com/63798882/150651255-21b8aaf5-6ec3-477b-ac82-33cacbc54df3.png)
