### ISSUE TITLE
RSEA-3323 | Squad Redesign | Home | Mobile | Buscador Voo | Sugestões de embarque divergem do Portal.

### ISSUE THREAD

**Issue by frederico-reis-softvaro** [henrique-softvaro/bugs-release-r1-2021#33]
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/84351890/151181758-65ce19b1-d640-49b2-a3fe-473678fac6fd.png">

![image](https://user-images.githubusercontent.com/84351890/151221206-4e7047f8-4d11-4263-b412-18e0d4ae1421.png)

**Comment by heliofazollo** [comment]
![Captura de Tela 2022-01-22 às 15 10 09](https://user-images.githubusercontent.com/63798882/150650614-08f7987b-0c91-4cfe-842e-15f55bc47ca2.png)
![Captura de Tela 2022-01-22 às 15 12 52](https://user-images.githubusercontent.com/63798882/150650615-b9181f25-078b-459d-8689-cb758201ee14.png)
![Captura de Tela 2022-01-22 às 15 13 43](https://user-images.githubusercontent.com/63798882/150650617-6db6560c-80e4-4ac2-baa4-245d074b0170.png)
![Captura de Tela 2022-01-22 às 15 14 06](https://user-images.githubusercontent.com/63798882/150650618-faf395bb-ba31-461d-b3a4-150b8acdaafe.png)

**Comment by frederico-reis-softvaro** [comment]
Reteste NOK.

No celular não está funcionando corretamente igual no Desktop, continuam divergentes
[RET_MobileAndroid_RSEA-3323_Geolocalização_Sugestões_v1.pdf](https://github.com/henrique-softvaro/bugs-release-r1-2021/files/7934536/RET_MobileAndroid_RSEA-3323_Geolocalizacao_Sugestoes_v1.pdf)
.
