### ISSUE TITLE
RSEA-3302 ela em branco na busca do destino

### ISSUE THREAD

**Issue by henrique-softvaro** [henrique-softvaro/bugs-release-r1-2021#5]
[Squad Redesign][Mobile IOS][Buscador] Tela em branco na busca do destino

**Comment by frederico-reis-softvaro** [comment]
[bug destino ios.pdf](https://github.com/henrique-softvaro/bugs-release-r1-2021/files/7915491/bug.destino.ios.pdf)

**Comment by frederico-reis-softvaro** [comment]
https://user-images.githubusercontent.com/86992602/151061780-dab01052-813f-4ff8-9cc9-84f3c2d50132.mov

Tela em branco ao clicar para pesquisar aeroportos resolvido
