### ISSUE TITLE
Buscador de voos na menor tela(320px) em smiles.com/home-v2 fica com em cima do logo e menu mobile

### ISSUE THREAD

**Issue by walacefex** [henrique-softvaro/bugs-release-r1-2021#62]
![image](https://user-images.githubusercontent.com/16948390/152015067-58ae2623-3206-4d42-b4e5-6fe81a59612a.png)

**Comment by frederico-reis-softvaro** [comment]
Esperando o Zé pra ver

**Comment by walacefex** [comment]
Em UAT5 está no formato correto, por causa do posicionamento do lazy-loading
